// Car inventory data for Big Five Car Sales
const carsData = [
    {
        id: 1,
        make: 'Aston Martin',
        model: 'DB11',
        year: 2022,
        price: 'Available on Request',
        image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        badge: 'Sports Car Excellence',
        category: 'luxury-sports',
        features: ['V8 Twin-Turbo', 'Carbon Fiber', 'Premium Leather', 'Advanced Tech'],
        description: 'The pinnacle of British luxury and performance, featuring handcrafted excellence and timeless design.',
        specs: {
            engine: '4.0L V8 Twin-Turbo',
            power: '503 HP',
            torque: '675 Nm',
            transmission: '8-Speed Automatic',
            drivetrain: 'RWD',
            acceleration: '4.0s 0-100km/h',
            topSpeed: '301 km/h',
            fuelConsumption: '11.4L/100km'
        },
        exterior: 'Magnetic Silver',
        interior: 'Obsidian Black Leather',
        mileage: 0,
        condition: 'Brand New',
        featured: true
    },
    {
        id: 2,
        make: 'Toyota',
        model: 'Land Cruiser Prado VX-R',
        year: 2024,
        price: 'Available on Request',
        image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        badge: 'Luxury Mid-Size SUV',
        category: 'luxury-suv',
        features: ['V6 Engine', '4WD System', 'Premium Interior', 'Safety Tech'],
        description: 'Ultimate luxury SUV combining legendary reliability with premium comfort and advanced technology.',
        specs: {
            engine: '4.0L V6 Naturally Aspirated',
            power: '275 HP',
            torque: '381 Nm',
            transmission: '6-Speed Automatic',
            drivetrain: 'Full-Time 4WD',
            acceleration: '9.7s 0-100km/h',
            topSpeed: '180 km/h',
            fuelConsumption: '12.4L/100km'
        },
        exterior: 'Pearl White',
        interior: 'Black Leather with Wood Trim',
        mileage: 0,
        condition: 'Brand New',
        featured: true
    },
    {
        id: 3,
        make: 'Ford',
        model: 'Ranger Raptor',
        year: 2023,
        price: 'Available on Request',
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        badge: 'Performance Off-Road',
        category: 'performance-truck',
        features: ['Raptor Suspension', 'Terrain Management', 'Sport Mode', 'Premium Audio'],
        description: 'The ultimate performance pickup, engineered for extreme off-road capability and on-road comfort.',
        specs: {
            engine: '3.0L V6 EcoBoost',
            power: '392 HP',
            torque: '583 Nm',
            transmission: '10-Speed Automatic',
            drivetrain: '4WD',
            acceleration: '6.4s 0-100km/h',
            topSpeed: '170 km/h',
            fuelConsumption: '10.7L/100km'
        },
        exterior: 'Code Orange',
        interior: 'Ebony Active X Trim',
        mileage: 1200,
        condition: 'Excellent',
        featured: true
    },
    {
        id: 4,
        make: 'Range Rover',
        model: 'HSE D350',
        year: 2024,
        price: 'Available on Request',
        image: 'https://images.unsplash.com/photo-1606016159991-8b5d5c6e0b7a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        badge: 'Luxury & Power',
        category: 'luxury-suv',
        features: ['Air Suspension', 'Terrain Response', 'Meridian Audio', 'Panoramic Roof'],
        description: 'The epitome of luxury SUV design, combining unparalleled comfort with exceptional capability.',
        specs: {
            engine: '3.0L I6 Diesel',
            power: '350 HP',
            torque: '700 Nm',
            transmission: '8-Speed Automatic',
            drivetrain: 'Intelligent AWD',
            acceleration: '6.1s 0-100km/h',
            topSpeed: '225 km/h',
            fuelConsumption: '8.6L/100km'
        },
        exterior: 'Byron Blue Metallic',
        interior: 'Ebony/Ivory Windsor Leather',
        mileage: 0,
        condition: 'Brand New',
        featured: true
    },
    {
        id: 5,
        make: 'Toyota',
        model: 'Land Cruiser 79 Series',
        year: 2024,
        price: 'Available on Request',
        image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        badge: 'Ultimate Off-Road',
        category: 'off-road-utility',
        features: ['Solid Axles', 'Manual Transmission', 'Diff Locks', 'Heavy Duty'],
        description: 'The legendary workhorse, built for the toughest conditions with unmatched durability and reliability.',
        specs: {
            engine: '4.5L V8 Turbo Diesel',
            power: '202 HP',
            torque: '650 Nm',
            transmission: '5-Speed Manual',
            drivetrain: 'Part-Time 4WD',
            acceleration: '12.1s 0-100km/h',
            topSpeed: '155 km/h',
            fuelConsumption: '11.8L/100km'
        },
        exterior: 'French Vanilla',
        interior: 'Charcoal Fabric',
        mileage: 0,
        condition: 'Brand New',
        featured: true
    },
    {
        id: 6,
        make: 'Mercedes-Benz',
        model: 'G63 AMG',
        year: 2024,
        price: 'Available on Request',
        image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
        badge: 'Magno Black Edition',
        category: 'luxury-performance',
        features: ['AMG V8 Biturbo', '3 Diff Locks', 'AMG Ride Control', 'Exclusive Interior'],
        description: 'The iconic G-Wagon with AMG performance, combining luxury with unmatched off-road capability.',
        specs: {
            engine: '4.0L V8 Biturbo',
            power: '585 HP',
            torque: '850 Nm',
            transmission: '9-Speed AMG Speedshift',
            drivetrain: 'Permanent AWD',
            acceleration: '4.5s 0-100km/h',
            topSpeed: '220 km/h',
            fuelConsumption: '13.1L/100km'
        },
        exterior: 'Magno Night Black',
        interior: 'Nappa Leather Red/Black',
        mileage: 0,
        condition: 'Brand New',
        featured: true
    },
    {
        id: 7,
        make: 'BMW',
        model: 'X7 M50i',
        year: 2024,
        price: 'Available on Request',
        image: 'https://via.placeholder.com/400x250/23313d/037db6?text=Premium+Luxury+SUV',
        badge: 'Elite Performance',
        category: 'luxury-suv',
        features: ['M Performance', 'xDrive AWD', '7-Seater', 'Executive Lounge'],
        description: 'Ultimate luxury SUV combining M Performance with exceptional comfort and cutting-edge technology.',
        specs: {
            engine: '4.4L V8 TwinPower Turbo',
            power: '530 HP',
            torque: '750 Nm',
            transmission: '8-Speed Steptronic',
            drivetrain: 'xDrive AWD',
            acceleration: '4.7s 0-100km/h',
            topSpeed: '250 km/h',
            fuelConsumption: '12.5L/100km'
        },
        exterior: 'Carbon Black Metallic',
        interior: 'Merino Leather Cognac',
        mileage: 0,
        condition: 'Brand New',
        featured: false
    },
    {
        id: 8,
        make: 'Toyota',
        model: 'Hilux GR-Sport',
        year: 2024,
        price: 'Available on Request',
        image: 'https://via.placeholder.com/400x250/23313d/037db6?text=2024+Toyota+Hilux+GR',
        badge: 'Rugged & Stylish',
        category: 'performance-pickup',
        features: ['GR Tuned Suspension', 'Sport Styling', 'Enhanced Interior', 'Off-Road Package'],
        description: 'The legendary Hilux enhanced by Gazoo Racing for superior performance and distinctive style.',
        specs: {
            engine: '2.8L Turbo Diesel',
            power: '204 HP',
            torque: '500 Nm',
            transmission: '6-Speed Automatic',
            drivetrain: '4WD',
            acceleration: '10.7s 0-100km/h',
            topSpeed: '175 km/h',
            fuelConsumption: '8.9L/100km'
        },
        exterior: 'Emotional Red',
        interior: 'Black Leather with Red Stitching',
        mileage: 0,
        condition: 'Brand New',
        featured: false
    },
    {
        id: 9,
        make: 'Toyota',
        model: 'Land Cruiser Prado',
        year: 2023,
        price: 'Available on Request',
        image: 'https://via.placeholder.com/400x250/23313d/037db6?text=Toyota+Prado+White',
        badge: 'Versatile Luxury',
        category: 'luxury-suv',
        features: ['Multi-Terrain Select', 'Crawl Control', 'Premium Audio', 'Safety Sense'],
        description: 'Versatile luxury SUV that excels in both urban sophistication and off-road adventure.',
        specs: {
            engine: '4.0L V6 Naturally Aspirated',
            power: '275 HP',
            torque: '381 Nm',
            transmission: '6-Speed Automatic',
            drivetrain: 'Full-Time 4WD',
            acceleration: '9.7s 0-100km/h',
            topSpeed: '180 km/h',
            fuelConsumption: '12.4L/100km'
        },
        exterior: 'Crystal Pearl',
        interior: 'Black Leather',
        mileage: 2500,
        condition: 'Excellent',
        featured: false
    }
];

// Featured cars (subset of main inventory)
const featuredCars = carsData.filter(car => car.featured);

// Export data for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { carsData, featuredCars };
}